# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver = "2"
members = ["common", "lua"]

[workspace.dependencies]
serde_json = "1.0.114"
