/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.datatower.sdk;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.*;
import java.util.HashMap;
import java.util.Map;

class DTTest {
    @Test void itWorks() throws IOException {
//        DTLogConsumer consumer = new DTLogConsumer("testing_logs", 200, "dt_test", 10*1024*1024);
//        DTAnalytics dt = new DTAnalytics(consumer, true);
//
//        HashMap<String, Object> properties = new HashMap<>();
//        properties.put("#app_id", "appidid");
//        properties.put("#bundle_id", "com.example");
//        properties.put("prooo", "hool");
//        dt.track("xxx", null, "event_test_java_sdk", properties);
//        dt.flush();
//        dt.close();
//
//        File dir = new File("testing_logs");
//        File[] foundFiles = dir.listFiles(new FilenameFilter() {
//            @Override
//            public boolean accept(File dir, String name) {
//                return name.startsWith("dt_test");
//            }
//        });
//        assert(foundFiles != null);
//        assert(foundFiles.length > 0);
//        File logFile = foundFiles[0];
//        try {
//            Gson gson = new Gson();
//            JsonReader reader = new JsonReader(new FileReader(logFile));
//            Map<String, Object> event = gson.fromJson(reader, Map.class);
//            assertEquals(event.getOrDefault("#app_id", "X"), "appidid");
//            assertEquals(event.getOrDefault("#bundle_id", "X"), "com.example");
//            assertEquals(event.getOrDefault("#event_name", "X"), "event_test_java_sdk");
//            assertEquals(event.getOrDefault("#dt_id", "X"), "xxx");
//            Object rawProps = event.get("properties");
//            assertInstanceOf(Map.class, rawProps);
//            Map<String, Object> props = (Map<String, Object>) rawProps;
//            assertEquals(props.getOrDefault("prooo", "X"), "hool");
//        } catch (FileNotFoundException t) {
//            t.printStackTrace();
//            assert(false);
//        } finally {
//            dir.delete();
//        }
    }
}
