[package]
name = "common"
version = "0.1.0"
edition = "2021"
build = "build/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
regex = "1.10.3"
once_cell = "1.19.0"

[build-dependencies]
cfg-if = "1.0.0"

[features]
default = ["log-consumer"]
log-consumer = []