/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function init(consumer: Consumer, debug?: boolean | undefined | null): boolean
export function track(dtId: string, acId: string, eventName: string, properties: Record<string, any>): boolean
export function userSet(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userSetOnce(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userAdd(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userUnset(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userDelete(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userAppend(dtId: string, acId: string, properties: Record<string, any>): boolean
export function userUniqAppend(dtId: string, acId: string, properties: Record<string, any>): boolean
export function flush(): void
export function close(): void
export function toggleLogger(enable: boolean): void
export class Consumer {
  static DTLogConsumer(path: string, maxBatchLen: number, namePrefix?: string | undefined | null, maxFileSizeBytes?: number | undefined | null): Consumer
  static DTMmapLogConsumer(path: string, namePrefix?: string | undefined | null, maxFileSizeBytes?: number | undefined | null, flushSizeBytes?: number | undefined | null): Consumer
}
