name: "PR CI"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  version_check:
    name: Version test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run version_test.sh
        run: |
          chmod +x ./.github/scripts/version_check.sh && ./.github/scripts/version_check.sh
        shell: bash